version: '3.8'

services:
    fastapi:
        build: fastapi/
        volumes:
            - .:/usr/src/app
        ports: 
            - 8008:8008
        networks:
            - deploy_network
        container_name: fastapi

    streamlit:
        build: streamlit/
        volumes:
            - .:/usr/src/app
        depends_on:
            - fastapi
        ports: 
            - 8501:8501
        networks:
            - deploy_network
        container_name: streamlit

networks:
    deploy_network:
        driver: bridge